stages:
  - build
  - test
  - deploy

build_image:
  stage: build
  script:
    - docker build -t bifrostuzh-proxy .
  only:
    - master

test:
  stage: test
  script:
    - docker run bifrostuzh-proxy npm test
  only:
    - master

publish:
  stage: deploy
  script:
    - docker tag -f bifrostuzh-proxy bifrostuzh/proxy
    - docker push bifrostuzh/proxy
  only:
    - master