stages:
  - build
  - test
  - deploy

build_image:
  stage: build
  script:
    - docker build -t bifrost-proxy .
  only:
    - master

test:
  stage: test
  script:
    - docker run bifrost-proxy npm test
  only:
    - master

publish:
  stage: deploy
  script:
    - docker tag -f bifrost-proxy localhost:5000/bifrost/proxy
    - docker push localhost:5000/bifrost/proxy
  only:
    - master